### ISSUE TITLE
Remove inferred equivalences

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-ontology#12]
The `relation-graph` produce produces classes that are subclasses of each other. Here is the output from `nmdco-relation-graph.owl`:  

`fluid astronomical body part` is a subclass of `compound astronomical body part`:

![image](https://user-images.githubusercontent.com/3186638/130693097-21bfdec8-a62d-42fc-9178-8e16a0ee6ed3.png)

And `compound astronomical body part` is a subclass of `fluid astronomical body part`:

![image](https://user-images.githubusercontent.com/3186638/130693289-8feee062-db16-4e76-af15-726bfa47a926.png)

Unfortunately, I can't use `robot reason` b/c of incoherencies in ENVO. PO uses the domain and range constraints from RO. And the addition of these domains causes unsatisfiable classes, and a DL profile error. A ticket about lack of domain/range constraints has been filed for ENVO: https://github.com/EnvironmentOntology/envo/issues/1182

But, there has not been follow up.

Jim B. suggested I could make a "base" version of PO, using robot like so:
```
pr-base.ttl: pro_nonreasoned.obo
    $(ROBOT) remove --input $< \
        --base-iri 'http://purl.obolibrary.org/obo/PR_' \
        --axioms external \
        --preserve-structure false \
        --trim false \
        --output $@
```

cc @cmungall @turbomam

**Comment by cmungall** [comment]
I have a whole blog post on this issue? :-) https://douroucouli.wordpress.com/2018/09/04/debugging-ontologies-using-owl-reasoning-part-2-unintentional-entailed-equivalence/
