### ISSUE TITLE
Review this repository to see if it is still needed and how we'd go about keeping it up to date. 

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-ontology#15]
In discussions about getting a new release of ENVO and searching in the data portal I realized we have terms in mongo,  for env_broad_scale, env_local_scale and env_medium,  that are not searchable in the data portal. @pkalita-lbl  looked at the nmdc-server code and determined that data portal ingest is dependent on https://raw.githubusercontent.com/microbiomedata/nmdc-ontology/main/nmdco-classes.json which has not been updated in 3 years. 

We need to 
- [ ] update this file, making sure to include other trusted ontologies 
- [ ] consider making versioned releases, the data portal code currently just points to the main branch

acceptance criteria: new json should include new terms such as 'stream water'

fyi @naglepuff @cmungall @jeffbaumes

**Comment by turbomam** [comment]
requires these system dependencies:
- [robot](https://robot.obolibrary.org/) (and a JVM)
- [relation-graph](https://github.com/INCATools/relation-graph), which is distributed as a Scala source

good opportunity for somebody to dockerize

**Comment by ssarrafan** [comment]
@aclum @turbomam since this was only assigned 3 days ago I will move it to the next sprint. If this is not actively being worked on, or if it should be re-assigned to someone else, please let me know.

**Comment by ssarrafan** [comment]
@aclum @turbomam doesn't appear to be active? Is this a high priority or should it be in the backlog?

**Comment by aclum** [comment]
This is a priority. We need to make sure that envo terms that are in mongo are searchable in the data portal. @ssarrafan  please add to GSP board.

**Comment by ssarrafan** [comment]
> This is a priority. We need to make sure that envo terms that are in mongo are searchable in the data portal. @ssarrafan please add to GSP board.


Ok I've added it to the ECR/GSP board. FYI @turbomam

**Comment by aclum** [comment]
@turbomam  can this be closed? I can find 'stream water' in the data portal now.

**Comment by turbomam** [comment]
Yeah. I still have some more exploration and updating to do in the schema code, but I can remember that without this issue.
