### ISSUE TITLE
subsetting of EnvO terms specific to MIxS soil package

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-ontology#2]
Create a subset of terms for use in the MIxS triad to use with soil package submissions.

process:
- use sparql query to extract subset of terms from the biome and astronomical body part hierarchies 
- produce a TSV / google sheet for review

cc @cmungall @dehays

**Comment by cmungall** [comment]
Spreadsheet https://docs.google.com/spreadsheets/d/1WErXj8sM5uJi51VVLNQZDilDF7wMiyBC2T4zELp7Axc/edit#gid=1239761730

**Comment by elishawc** [comment]
Per @cmungall 's email and the subset being easier to review, I am doing some additional triage of terms.

**Comment by cmungall** [comment]
my comments from email 

Do you have your inclusion/exclusion criteria documented?

Sometimes it seems over-specific, sometimes over-generic

As an example, of over-specific:

UNEP-WCMC class 1 mountain	A high-elevation mountain which has a maximum elevation greater than 4500 metres above sea level.
UNEP-WCMC class 2 mountain	A high-elevation mountain which has a maximum elevation between 3500 and 4500 metres above sea level.
UNEP-WCMC class 3 mountain	A high-elevation mountain which has a maximum elevation between 2500 and 3500 metres above sea level.
UNEP-WCMC class 4 mountain	A mid-elevation mountain which has a maximum elevation between 1500 and 2499 metres above sea level and a slope greater than or equal to two degrees.
UNEP-WCMC class 5 mountain	A mid-elevation mountain which has a maximum elevation between 1000 and 1499 metres above sea level and either 1) a slope greater than or equal to five degrees or 2) a local elevation range, within a 7 kilometre radius, of greater than 300 metres above sea level.
UNEP-WCMC class 6 mountain	A mid-elevation mountain which has a maximum elevation between 300 and 999 metres above sea level and a local elevation range, within a 7 kilometre radius, of greater than 300 metres above sea level.
UNEP-WCMC class 7 mountain	An elevated inner basin or plateau surrounded by mountains, but not - itself - a mountain.

I don't believe this level of specificity has ever been used in the history of sample submission to INSDC. I would just use the ENVO concept for mountain. What does the level of specifcity here buy us? Note that we have a distinct elevation field.

An example of too generic:

env_local_scale	<http://purl.obolibrary.org/obo/ENVO_01000755>	aeroform	A part of an astronomical body which is primarily composed of a continuous volume of gaseous or aerosolised material held in shape by one or more environmental processes.	Air	

As you can see in OLS, this is a grouping for "tornado" and "fire whirl". These would seem like better levels of granularity, and likely to encompass different environments

(I also find myself wondering about the logistics of collecting from a tornado)

Similarly

env_local_scale	<http://purl.obolibrary.org/obo/ENVO_01000105>	marine benthic feature	A prominent or distinctive aspect, quality, or characteristic of environments occurring on or along marine benthic environments.	Sediment|Water	

this is quite a generic sounding term, and is redundant with the biome annotation which would be presumably "marine benthic biome"

**Comment by ssarrafan** [comment]
Discussed at metadata meeting today and will close this issue per Slack with @elishawc.  @turbomam will create a new issue for the next steps.
