### ISSUE TITLE
What is 'root node', `http://purl.obolibrary.org/obo/NMDCO_00000000` and why isn't it the root?

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-ontology#37]

**Comment by wdduncan** [comment]
To be honest, I can't recall why it is there. I think it might have needed for OLS.

**Comment by turbomam** [comment]
Thanks for replying @wdduncan 

This resource is great. If you have feedback, I'm happy to use it, but I didn't mean to imply I expect you to help me with every issue!

**Comment by turbomam** [comment]
deleted NMDCO_00000000

moved owl:Thing danglers into BFO entity
