### ISSUE TITLE
create json file for Kitware

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-ontology#4]
Kitware needs a json file (similar to `envo-basic.json`) for ingest into the data portal. Since this file can include classes outside of `envo`, I will create this file in the `nmdc-ontology` repo.

For background see this `envo` ticket: https://github.com/EnvironmentOntology/envo/issues/1198

cc @cmungall @turbomam @jeffbaumes

**Comment by ssarrafan** [comment]
Moved to 'in progress' since Bill reported working on this yesterday and today.

**Comment by wdduncan** [comment]
@jeffbaumes see the `nmco.json` and `nmdco-classes.json` files.   
Let me know if these work for you.

**Comment by jeffbaumes** [comment]
Thanks, we will take a look. I cross-linked this over to https://github.com/microbiomedata/nmdc-server/issues/361
